name: secrets and variables

on: workflow_dispatch
jobs:
    Staging-environment:
        runs-on: ubuntu-22.04
        environment: staging
        env:
            # secrets
            EXAMPLE_ENVIRONMENT_SECRET: ${{secrets.EXAMPLE_ENVIRONMENT_SECRET}}
            EXAMPLE_REPOSITORY_SECRET: ${{secrets.EXAMPLE_REPOSITORY_SECRET}}
            # variables
            EXAMPLE_ENVIRONMENT_VARIABLE: ${{vars.EXAMPLE_ENVIRONMENT_VARIABLE}}
            EXAMPLE_REPOSITORY_VARIABLE: ${{vars.EXAMPLE_REPOSITORY_VARIABLE}}
        steps:
            - name: "Inspect Values inside job"
              run: |
                echo "EXAMPLE_ENVIRONMENT_SECRET: $EXAMPLE_ENVIRONMENT_SECRET"
                echo "EXAMPLE_REPOSITORY_SECRET: $EXAMPLE_REPOSITORY_SECRET"
                ech "###########################################################"
                echo "EXAMPLE_ENVIRONMENT_VARIABLE: $EXAMPLE_ENVIRONMENT_VARIABLE"
                echo "EXAMPLE_REPOSITORY_VARIABLE: $EXAMPLE_REPOSITORY_VARIABLE" 
    Production-environment:
        runs-on: ubuntu-22.04
        environment: production
        env:
            # secrets
            EXAMPLE_ENVIRONMENT_SECRET: ${{secrets.EXAMPLE_ENVIRONMENT_SECRET}}
            EXAMPLE_REPOSITORY_SECRET: ${{secrets.EXAMPLE_REPOSITORY_SECRET}}
            # variables
            EXAMPLE_ENVIRONMENT_VARIABLE: ${{vars.EXAMPLE_ENVIRONMENT_VARIABLE}}
            EXAMPLE_REPOSITORY_VARIABLE: ${{vars.EXAMPLE_REPOSITORY_VARIABLE}}
        steps:
            - name: "Inspect Values inside job"
              run: |
                echo "EXAMPLE_ENVIRONMENT_SECRET: $EXAMPLE_ENVIRONMENT_SECRET"
                echo "EXAMPLE_REPOSITORY_SECRET: $EXAMPLE_REPOSITORY_SECRET"
                ech "###########################################################"
                echo "EXAMPLE_ENVIRONMENT_VARIABLE: $EXAMPLE_ENVIRONMENT_VARIABLE"
                echo "EXAMPLE_REPOSITORY_VARIABLE: $EXAMPLE_REPOSITORY_VARIABLE" 

